name: CI

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Load .env file
      run: echo "URLS=$(grep URLS .env | cut -d '=' -f2)" >> $GITHUB_ENV

    - name: Ping URLs
      run: npm run ping
