name: ago-render-Health-Check

on:
  schedule:
    - cron: '0 */5 * * *'  # Runs every 5 hours
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log timestamp
      run: echo "Cron triggered at $(date)"

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Load .env file
      run: echo "URLS=$(grep URLS .env | cut -d '=' -f2)" >> $GITHUB_ENV

    - name: Ping URLs
      run: npm run ping
